using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

namespace SystemSage {
  static class StyledPdfReport {
    sealed class Line { public string Text; public bool Heading; public Line(string text,bool heading){Text=text;Heading=heading;} }
    public static string Write(DiagnosticReport report){string dir=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments),"SystemSage Reports");Directory.CreateDirectory(dir);string path=Path.Combine(dir,"SystemSage-PC-Health-"+DateTime.Now.ToString("yyyyMMdd-HHmmss")+".pdf");var lines=new List<Line>();lines.Add(new Line("Generated "+report.Created.ToString("yyyy-MM-dd HH:mm:ss")+"   |   Recent events "+report.ErrorCount+"   |   Device warnings "+report.WarningCount,false));foreach(var section in report.Sections){lines.Add(new Line(section.Title.ToUpperInvariant(),true));if(section.Rows.Count==0)lines.Add(new Line("No issues found.",false));foreach(var row in section.Rows){string value=String.Join("  |  ",row.Select(Ascii));foreach(string wrapped in Wrap(value,104))lines.Add(new Line(wrapped,false));}}Build(path,lines);return path;}
    static string Ascii(string value){var b=new StringBuilder();foreach(char c in value??"")b.Append(c>=32&&c<=126?c:'?');return b.ToString();}
    static IEnumerable<string> Wrap(string text,int width){while(text.Length>width){int cut=text.LastIndexOf(' ',width);if(cut<1)cut=width;yield return text.Substring(0,cut);text=text.Substring(cut).TrimStart();}yield return text;}
    static string Escape(string value){return value.Replace("\\","\\\\").Replace("(","\\(").Replace(")","\\)");}
    static byte[] A(string value){return Encoding.ASCII.GetBytes(value);}
    static void W(Stream stream,string value){byte[] bytes=A(value);stream.Write(bytes,0,bytes.Length);}
    static List<List<Line>> Paginate(List<Line> lines){var pages=new List<List<Line>>();var current=new List<Line>();int used=0;foreach(Line line in lines){int cost=line.Heading?25:12;if(current.Count>0&&used+cost>640){pages.Add(current);current=new List<Line>();used=0;}current.Add(line);used+=cost;}if(current.Count>0)pages.Add(current);return pages;}
    static void Build(string path,List<Line> lines){var pages=Paginate(lines);int pageCount=pages.Count;var objects=new List<byte[]>();objects.Add(A("<< /Type /Catalog /Pages 2 0 R >>"));string kids=String.Join(" ",Enumerable.Range(0,pageCount).Select(i=>(3+i*2)+" 0 R"));objects.Add(A("<< /Type /Pages /Kids ["+kids+"] /Count "+pageCount+" >>"));int regularId=3+pageCount*2,boldId=regularId+1;for(int page=0;page<pageCount;page++){int pageId=3+page*2,contentId=pageId+1;objects.Add(A("<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 "+regularId+" 0 R /F2 "+boldId+" 0 R >> >> /Contents "+contentId+" 0 R >>"));var c=new StringBuilder();c.Append("0.09 0.10 0.08 rg 0 724 612 68 re f ");c.Append("0.73 1 0.27 rg 0 724 9 68 re f ");c.Append("BT /F2 20 Tf 0.73 1 0.27 rg 34 758 Td (SYSTEMSAGE) Tj ET ");c.Append("BT /F1 9 Tf 1 1 1 rg 34 740 Td (COMPLETE PC HEALTH REPORT) Tj ET ");int y=700;foreach(Line line in pages[page]){if(line.Heading){c.Append("0.94 0.95 0.92 rg 30 "+(y-5)+" 552 19 re f ");c.Append("0.09 0.10 0.08 rg BT /F2 9 Tf 39 "+y+" Td ("+Escape(line.Text)+") Tj ET ");y-=25;}else{c.Append("0.20 0.22 0.19 rg BT /F1 8 Tf 39 "+y+" Td ("+Escape(line.Text)+") Tj ET ");y-=12;}}c.Append("0.82 0.84 0.80 RG 30 28 m 582 28 l S ");c.Append("0.38 0.40 0.36 rg BT /F1 7 Tf 30 16 Td (READ-ONLY LOCAL DIAGNOSTIC - NO DATA UPLOADED) Tj ET ");c.Append("BT /F1 7 Tf 535 16 Td (Page "+(page+1)+" of "+pageCount+") Tj ET ");byte[] stream=A(c.ToString());objects.Add(A("<< /Length "+stream.Length+" >>\nstream\n"+c+"\nendstream"));}objects.Add(A("<< /Type /Font /Subtype /Type1 /BaseFont /Courier >>"));objects.Add(A("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>"));using(var output=new FileStream(path,FileMode.Create,FileAccess.Write)){W(output,"%PDF-1.4\n");var offsets=new List<long>{0};for(int i=0;i<objects.Count;i++){offsets.Add(output.Position);W(output,(i+1)+" 0 obj\n");output.Write(objects[i],0,objects[i].Length);W(output,"\nendobj\n");}long xref=output.Position;W(output,"xref\n0 "+(objects.Count+1)+"\n0000000000 65535 f \n");for(int i=1;i<offsets.Count;i++)W(output,offsets[i].ToString("0000000000")+" 00000 n \n");W(output,"trailer << /Size "+(objects.Count+1)+" /Root 1 0 R >>\nstartxref\n"+xref+"\n%%EOF");}}
  }
}
