using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Management;
using System.Net.NetworkInformation;
using System.Net;
using System.Text.RegularExpressions;
using Microsoft.Win32;
using System.Threading;

namespace SystemSage {
  static class Ui {
    public static void Header(string title) {
      if(!Console.IsOutputRedirected)try{Console.Clear();}catch{} Console.ForegroundColor=ConsoleColor.Green;
      Console.WriteLine("  ____            _                 ____");
      Console.WriteLine(" / ___| _   _ ___| |_ ___ _ __ ___/ ___|  __ _  __ _  ___");
      Console.WriteLine(" \\___ \\| | | / __| __/ _ \\ '_ ` _ \\___ \\ / _` |/ _` |/ _ \\");
      Console.WriteLine("  ___) | |_| \\__ \\ ||  __/ | | | | |___) | (_| | (_| |  __/");
      Console.WriteLine(" |____/ \\__, |___/\\__\\___|_| |_| |_|____/ \\__,_|\\__, |\\___|");
      Console.WriteLine("        |___/                                  |___/");
      Console.ResetColor(); Console.WriteLine(" Lightweight Windows diagnostics  |  MIT open source\n");
      if(!String.IsNullOrEmpty(title)){Console.ForegroundColor=ConsoleColor.White;Console.WriteLine(" "+title.ToUpperInvariant());Console.ForegroundColor=ConsoleColor.DarkGray;Console.WriteLine(" "+new string('-',Math.Min(70,title.Length+8)));Console.ResetColor();}
    }
    static int progressLength;
    public static void Progress(int percent,string label){if(Console.IsOutputRedirected)return;percent=Math.Max(0,Math.Min(100,percent));int width=Math.Max(12,Math.Min(34,SafeWidth()-38));int filled=(int)Math.Round(width*percent/100.0);string line=" ["+new string('#',filled)+new string('-',width-filled)+"] "+percent.ToString().PadLeft(3)+"%  "+label;int available=Math.Max(20,SafeWidth()-1);if(line.Length>available)line=line.Substring(0,Math.Max(1,available-3))+"...";Console.Write("\r"+line.PadRight(Math.Max(progressLength,line.Length)));progressLength=Math.Max(progressLength,line.Length);if(percent>=100){Console.WriteLine();progressLength=0;}}
    public static T Loading<T>(string label,Func<T> action){if(Console.IsOutputRedirected)return action();bool done=false;Exception failure=null;T result=default(T);var worker=new Thread(()=>{try{result=action();}catch(Exception e){failure=e;}finally{done=true;}});worker.Start();string[] frames={"|","/","-","\\"};int i=0;while(!done){string line=" ["+frames[i++%frames.Length]+"] "+label;Console.Write("\r"+line.PadRight(Math.Max(progressLength,line.Length)));progressLength=Math.Max(progressLength,line.Length);Thread.Sleep(90);}Console.Write("\r"+new string(' ',progressLength)+"\r");progressLength=0;if(failure!=null)throw failure;Console.ForegroundColor=ConsoleColor.Green;Console.WriteLine(" [OK] "+label);Console.ResetColor();return result;}
    public static void Pair(string name,string value){Console.ForegroundColor=ConsoleColor.DarkGray;Console.Write((" "+name).PadRight(23));Console.ResetColor();Console.WriteLine(value);}
    public static void Table(string[] heads,List<string[]> rows){int width=Math.Max(70,SafeWidth()-2),cols=heads.Length;int[] sizes=new int[cols];for(int i=0;i<cols;i++){sizes[i]=heads[i].Length;foreach(var r in rows)if(i<r.Length)sizes[i]=Math.Max(sizes[i],r[i]==null?0:r[i].Length);sizes[i]=Math.Min(sizes[i],Math.Max(12,width/cols));}Console.ForegroundColor=ConsoleColor.Green;WriteRow(heads,sizes);Console.ResetColor();Console.ForegroundColor=ConsoleColor.DarkGray;Console.WriteLine(" "+new string('-',Math.Min(width,sizes.Sum()+cols*2)));Console.ResetColor();foreach(var r in rows)WriteRow(r,sizes);}
    static void WriteRow(string[] row,int[] sizes){Console.Write(" ");for(int i=0;i<sizes.Length;i++){string v=i<row.Length?(row[i]??""):"";if(v.Length>sizes[i])v=v.Substring(0,Math.Max(1,sizes[i]-3))+"...";Console.Write(v.PadRight(sizes[i]+2));}Console.WriteLine();}
    static int SafeWidth(){try{return Console.WindowWidth;}catch{return 100;}}
    public static void Pause(){Console.ForegroundColor=ConsoleColor.DarkGray;Console.Write("\n Press any key to return...");Console.ResetColor();Console.ReadKey(true);}
  }

  static class Scan {
    public static int Cpu(){using(var c=new PerformanceCounter("Processor","% Processor Time","_Total")){c.NextValue();Thread.Sleep(400);return (int)Math.Round(c.NextValue());}}
    public static long[] Memory(){foreach(ManagementObject x in new ManagementObjectSearcher("SELECT TotalVisibleMemorySize,FreePhysicalMemory FROM Win32_OperatingSystem").Get()){long t=Convert.ToInt64(x["TotalVisibleMemorySize"])*1024,f=Convert.ToInt64(x["FreePhysicalMemory"])*1024;return new[]{t-f,t};}return new long[]{0,0};}
    public static string Bytes(long value){string[] u={"B","KB","MB","GB","TB"};double n=value;int i=0;while(n>=1024&&i<u.Length-1){n/=1024;i++;}return n.ToString(n>=100?"0":n>=10?"0.0":"0.00")+" "+u[i];}
    public static List<string[]> Processes(int limit){return Process.GetProcesses().Select(p=>{try{return new[]{p.ProcessName,p.Id.ToString(),Bytes(p.WorkingSet64),p.WorkingSet64.ToString(),p.Threads.Count.ToString()};}catch{return null;}}).Where(x=>x!=null).OrderByDescending(x=>Int64.Parse(x[3])).Take(limit).Select(x=>new[]{x[0],x[1],x[2],x[4]}).ToList();}
    public static List<string[]> Drives(){return DriveInfo.GetDrives().Where(d=>d.IsReady).Select(d=>new[]{d.Name,String.IsNullOrEmpty(d.VolumeLabel)?"Local disk":d.VolumeLabel,d.DriveFormat,Bytes(d.TotalSize-d.AvailableFreeSpace),Bytes(d.AvailableFreeSpace),Math.Round((double)(d.TotalSize-d.AvailableFreeSpace)/d.TotalSize*100)+"%"}).ToList();}
    public static List<string[]> Security(){var rows=new List<string[]>();try{foreach(ManagementObject x in new ManagementObjectSearcher("root\\SecurityCenter2","SELECT displayName,productState FROM AntivirusProduct").Get())rows.Add(new[]{Convert.ToString(x["displayName"]),"Registered","0x"+Convert.ToInt32(x["productState"]).ToString("X6")});}catch(Exception e){rows.Add(new[]{"Windows Security","Unavailable",e.Message});}return rows;}
    public static string[] Battery(){var p=System.Windows.Forms.SystemInformation.PowerStatus;int charge=(int)Math.Round(p.BatteryLifePercent*100);string health="Not exposed by firmware";try{double full=0,design=0;foreach(ManagementObject x in new ManagementObjectSearcher("root\\wmi","SELECT FullChargedCapacity FROM BatteryFullChargedCapacity").Get()){full=Convert.ToDouble(x["FullChargedCapacity"]);break;}foreach(ManagementObject x in new ManagementObjectSearcher("root\\wmi","SELECT DesignedCapacity FROM BatteryStaticData").Get()){design=Convert.ToDouble(x["DesignedCapacity"]);break;}if(design>0)health=Math.Round(full/design*100)+"%";}catch{}return new[]{charge+"%",health,p.PowerLineStatus==System.Windows.Forms.PowerLineStatus.Online?"Plugged in":"On battery",p.BatteryLifeRemaining>0?TimeSpan.FromSeconds(p.BatteryLifeRemaining).ToString(@"h\h\ m\m"):"Calculating"};}
    public static List<string[]> Network(){return IPGlobalProperties.GetIPGlobalProperties().GetActiveTcpConnections().OrderBy(x=>x.State).Take(100).Select(x=>new[]{x.State.ToString(),x.LocalEndPoint.ToString(),x.RemoteEndPoint.ToString()}).ToList();}
    public static List<string[]> Startup(){var rows=new List<string[]>();ReadRun(Registry.CurrentUser,"Current user",rows);ReadRun(Registry.LocalMachine,"All users",rows);return rows;}
    static void ReadRun(RegistryKey root,string scope,List<string[]> rows){using(var key=root.OpenSubKey("Software\\Microsoft\\Windows\\CurrentVersion\\Run")){if(key==null)return;foreach(string name in key.GetValueNames())rows.Add(new[]{name,scope,Convert.ToString(key.GetValue(name))});}}
    public static List<string[]> SystemInfo(){var rows=new List<string[]>();rows.Add(new[]{"Computer",Environment.MachineName});try{foreach(ManagementObject x in new ManagementObjectSearcher("SELECT Caption,Version,LastBootUpTime FROM Win32_OperatingSystem").Get()){rows.Add(new[]{"Windows",Convert.ToString(x["Caption"])+" "+Convert.ToString(x["Version"])});DateTime boot=ManagementDateTimeConverter.ToDateTime(Convert.ToString(x["LastBootUpTime"]));rows.Add(new[]{"Uptime",(DateTime.Now-boot).ToString(@"d\d\ h\h\ m\m")});break;}}catch{rows.Add(new[]{"Windows",Environment.OSVersion.VersionString});}rows.Add(new[]{"Architecture",Environment.Is64BitOperatingSystem?"64-bit":"32-bit"});rows.Add(new[]{"Logical processors",Environment.ProcessorCount.ToString()});try{foreach(ManagementObject x in new ManagementObjectSearcher("SELECT Manufacturer,Model FROM Win32_ComputerSystem").Get()){rows.Add(new[]{"Manufacturer",Convert.ToString(x["Manufacturer"])});rows.Add(new[]{"Model",Convert.ToString(x["Model"])});break;}}catch{}return rows;}
  }

  static class App {
    const string Version="1.2.0";
    public static int Main(string[] args){try{if(args.Length==0&&Environment.UserInteractive&&!Console.IsInputRedirected){if(CheckForUpdate())return 0;Menu();return 0;}return Command(args);}catch(Exception e){Console.ForegroundColor=ConsoleColor.Red;Console.Error.WriteLine("SystemSage: "+e.Message);Console.ResetColor();return 1;}}
    static bool CheckForUpdate(){try{ServicePointManager.SecurityProtocol|=(SecurityProtocolType)3072;var request=(HttpWebRequest)WebRequest.Create("https://api.github.com/repos/cyrstrstn/systemsage/releases/latest");request.UserAgent="SystemSage/"+Version;request.Timeout=2500;request.ReadWriteTimeout=2500;string json;using(var response=request.GetResponse())using(var reader=new StreamReader(response.GetResponseStream()))json=reader.ReadToEnd();var match=Regex.Match(json,"\\\"tag_name\\\"\\s*:\\s*\\\"v?([^\\\"]+)\\\"");if(!match.Success)return false;Version latest;if(!System.Version.TryParse(match.Groups[1].Value,out latest))return false;Version current;if(!System.Version.TryParse(Version,out current)||latest<=current)return false;Ui.Header("Update available");Console.ForegroundColor=ConsoleColor.Green;Console.WriteLine(" SystemSage "+latest+" is available");Console.ResetColor();Console.WriteLine(" Installed version: "+Version+"\n");Console.Write(" Press U to update now, or any other key to skip: ");if(Console.ReadKey(true).Key!=ConsoleKey.U)return false;Console.WriteLine("\n Starting the one-click updater...");string url="https://raw.githubusercontent.com/cyrstrstn/systemsage/main/scripts/irm-install.ps1?cache="+Guid.NewGuid().ToString("N");string command="$ProgressPreference='SilentlyContinue'; irm '"+url+"' | iex";Process.Start(new ProcessStartInfo("powershell.exe","-NoProfile -ExecutionPolicy Bypass -Command \""+command+"\""){UseShellExecute=true});return true;}catch{return false;}}
    static int Command(string[] args){string c=args.Length==0?"doctor":args[0].ToLowerInvariant();if(c=="--help"||c=="help"){Help();return 0;}if(c=="--version"){Console.WriteLine(Version);return 0;}if(c=="doctor"||c=="overview"){Overview();return 0;}if(c=="processes"){ShowProcesses();return 0;}if(c=="storage"){ShowStorage();return 0;}if(c=="security"){ShowSecurity();return 0;}if(c=="battery"){ShowBattery();return 0;}if(c=="network"){ShowNetwork();return 0;}if(c=="startup"){ShowStartup();return 0;}if(c=="system"){ShowSystem();return 0;}if(c=="report"){Report();return 0;}Console.Error.WriteLine("Unknown command: "+c+". Run systemsage --help.");return 2;}
    static void Menu(){int selected=0;string[] labels={"Complete PC health overview","Top processes","Storage usage","Security status","Battery health","Network connections","Startup programs","System details","Generate full PDF report","Exit"};while(true){Ui.Header("Diagnostic menu");for(int i=0;i<labels.Length;i++){if(i==selected){Console.BackgroundColor=ConsoleColor.DarkGreen;Console.ForegroundColor=ConsoleColor.White;Console.WriteLine(" > "+labels[i].PadRight(34));Console.ResetColor();}else Console.WriteLine("   "+labels[i]);}Console.ForegroundColor=ConsoleColor.DarkGray;Console.WriteLine("\n Arrow keys navigate  |  Enter selects  |  Q exits");Console.ResetColor();var k=Console.ReadKey(true);if(k.Key==ConsoleKey.UpArrow)selected=(selected+labels.Length-1)%labels.Length;else if(k.Key==ConsoleKey.DownArrow)selected=(selected+1)%labels.Length;else if(k.Key==ConsoleKey.Q||k.Key==ConsoleKey.Escape)return;else if(k.Key==ConsoleKey.Enter){if(selected==9)return;RunIndex(selected);Ui.Pause();}}}
    static void RunIndex(int i){if(i==0)Overview();else if(i==1)ShowProcesses();else if(i==2)ShowStorage();else if(i==3)ShowSecurity();else if(i==4)ShowBattery();else if(i==5)ShowNetwork();else if(i==6)ShowStartup();else if(i==7)ShowSystem();else Report();}
    static void Overview(){Ui.Header("Complete PC health overview");var report=FullDiagnostic.Collect(Ui.Progress);Ui.Progress(97,"Building readable PDF report");string pdf=StyledPdfReport.Write(report);Ui.Progress(100,"Diagnostic complete");FullDiagnostic.Print(report);Console.ForegroundColor=ConsoleColor.Green;Console.WriteLine("\n PDF report ready");Console.ResetColor();Console.WriteLine(" "+pdf);if(!Console.IsInputRedirected&&!Console.IsOutputRedirected){Console.Write("\n Press V to view the PDF, or any other key to continue: ");if(Console.ReadKey(true).Key==ConsoleKey.V)TryOpen(pdf);}}
    static void ShowProcesses(){Ui.Header("Top processes");Ui.Table(new[]{"Process","PID","Memory","Threads"},Ui.Loading("Reading running processes",()=>Scan.Processes(30)));}
    static void ShowStorage(){Ui.Header("Storage usage");Ui.Table(new[]{"Drive","Label","Format","Used","Available","Usage"},Ui.Loading("Reading connected drives",Scan.Drives));}
    static void ShowSecurity(){Ui.Header("Security status");Ui.Table(new[]{"Provider","Registration","State"},Ui.Loading("Checking Windows Security Center",Scan.Security));}
    static void ShowBattery(){Ui.Header("Battery health");var b=Ui.Loading("Reading battery telemetry",Scan.Battery);Ui.Pair("Current charge",b[0]);Ui.Pair("Estimated health",b[1]);Ui.Pair("Power state",b[2]);Ui.Pair("Time remaining",b[3]);}
    static void ShowNetwork(){Ui.Header("Network connections");Ui.Table(new[]{"State","Local endpoint","Remote endpoint"},Ui.Loading("Reading active TCP connections",Scan.Network));}
    static void ShowStartup(){Ui.Header("Startup programs");Ui.Table(new[]{"Name","Scope","Command"},Ui.Loading("Reading startup entries",Scan.Startup));}
    static void ShowSystem(){Ui.Header("System details");Ui.Table(new[]{"Property","Value"},Ui.Loading("Reading device identity",Scan.SystemInfo));}
    static void Report(){Ui.Header("Generate full PDF report");var report=FullDiagnostic.Collect(Ui.Progress);Ui.Progress(97,"Building readable PDF report");string path=StyledPdfReport.Write(report);Ui.Progress(100,"Report complete");Console.ForegroundColor=ConsoleColor.Green;Console.WriteLine(" [READY] PDF report saved");Console.ResetColor();Console.WriteLine(" "+path);if(!Console.IsInputRedirected&&!Console.IsOutputRedirected){Console.Write("\n Press V to view the PDF, or any other key to continue: ");if(Console.ReadKey(true).Key==ConsoleKey.V)TryOpen(path);}}
    static void TryOpen(string path){try{Process.Start(new ProcessStartInfo(path){UseShellExecute=true});}catch(Exception e){Console.WriteLine(" Could not open PDF: "+e.Message);}}
    static void Help(){Console.WriteLine("SystemSage "+Version+" - lightweight Windows diagnostics\n\nUsage:\n  systemsage                 Interactive menu\n  systemsage doctor          Complete PC overview and PDF\n  systemsage processes       Top memory processes\n  systemsage storage         Drive usage\n  systemsage security        Registered antivirus\n  systemsage battery         Charge and health\n  systemsage network         Active TCP connections\n  systemsage startup         Startup programs\n  systemsage system          Device details\n  systemsage report          Generate the full PDF report\n  systemsage --version       Print version");}
  }
}
